### ISSUE TITLE
Implement Reparametrized version of Normal

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#10]
PyTorch PR https://github.com/pytorch/pytorch/pull/3886

**Comment by fritzo** [comment]
@alicanb I added a paragraph to the [Design Doc](https://docs.google.com/document/d/1wnABg0cdyaVMr-Xqz_brHBwnPJuzTeSk3Oqko2HHSfE/edit#heading=h.u7a6f67mlqya) suggesting we add a `reparameterized=False` argument to the `__init__()` method of each distribution. This is nice since some distributions are much cheaper when not reparameterized. Does this sound reasonable?

**Comment by alicanb** [comment]
Yep, makes perfect sense.

**Comment by jwvdm** [comment]
Am I understanding correctly that we are now leaning towards `reparameterized` a class-level property, rather than a constructor argument? (see: [comment in pull req 21](https://github.com/probtorch/pytorch/pull/21#discussion_r152431244) )

**Comment by fritzo** [comment]
Done as of https://github.com/pytorch/pytorch/pull/4142
