### ISSUE TITLE
Implement Exponential distribution

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#11]

**Comment by fritzo** [comment]
It looks like there is already an `exponential_` sampler [implemented in PyTorch](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/methods/TensorRandom.cwrap#L195), at least at the C level. Do you have an understanding of how these samplers are organized?

**Comment by alicanb** [comment]
done as of https://github.com/pytorch/pytorch/pull/4234
