### ISSUE TITLE
Implement PowerTransform

### ISSUE THREAD

**Issue by alicanb** [probtorch/pytorch#114]

**Comment by vishwakftw** [comment]
Cannot this be as simple as:
`X --> Y = log(X)` --> `affine(Y, loc=0, scale=power) = Z` -->`exp(Z) = X**power`?

**Comment by vishwakftw** [comment]
@alicanb Are we going to be implementing this?

**Comment by alicanb** [comment]
Sure, want to take it?

**Comment by vishwakftw** [comment]
I think I can take it up. I will let you know otherwise soon.

**Comment by fritzo** [comment]
@vishwakftw if you submit a PR for `PowerTransform`, could you also rename `BoltzmannTransform` to `SoftmaxTransform` in that PR? I'd submit a PR for the renaming but I don't want to overload the PyTorch folks with too many tiny PRs.

**Comment by vishwakftw** [comment]
Closed in favour of https://github.com/pytorch/pytorch/pull/5976.
