### ISSUE TITLE
kl_divergence(Bernoulli(0), Bernoulli(0)) == NAN

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#117]
It looks like we could improve numerical stability of `kl_divergence()`.
- [x] `kl_divergence(Bernoulli(0), Bernoulli(0)) == 0` (currently NAN)
- [x] `kl_divergence(Bernoulli(0), Bernoulli(1)) == flaot('inf')` (currently NAN)
- [x] `Categorical`
- [x] `OneHotCategorical`
- [ ] `Poisson`

**Comment by fritzo** [comment]
@vishwakftw Do you want to look into this?

**Comment by vishwakftw** [comment]
@fritzo Sorry about the Bernoulli distribution. I have fixed it locally, and currently I am waiting for the build to complete for testing. W.R.T. the other, could you suggest what needs to be done?

**Comment by fritzo** [comment]
No worries :smile: I'm glad we could get the implementations merged early so we can test things in Pyro.

I think it would be good to have tests of edge cases as in Neeraj's `test_bernoulli_gradient`. Let's add something like `TestKL.test_edge_cases()` with a few tests like
```py
class TestKL(TestCase):
    def test_edge_cases(self):
        self.assertEqual(kl_divergence(Bernoulli(0), Bernoulli(0)), 0)
        self.assertEqual(kl_divergence(Bernoulli(0), Bernoulli(1)), float('inf'), allow_infinity=True)
        self.assertEqual(kl_divergence(
            Categorical(variable([0, 1])),
            Categorical(variable([0.5, 0.5]))), float('inf'), allow_infinity=True)
        ...
```

**Comment by vishwakftw** [comment]
Fixed. Closing in favour of https://github.com/pytorch/pytorch/pull/4961.
