### ISSUE TITLE
Implement differentiable .cdf() for univariate distributions

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#120]
This would allow generic implementation of reparameterized truncated distributions.

**Comment by vishwakftw** [comment]
I think if we add `.cdf()`, we can add autograd based tests for `.log_pdf()`.

**Comment by vishwakftw** [comment]
This is a checklist:
- [ ] Beta
- [X] Cauchy
- [ ] Dirichlet
- [X] Exponential
- [ ] F
- [ ] Gamma
- [X]  Gumbel
- [X] Laplace
- [X] Log Normal
- [X] Normal
- [X] Pareto
- [ ] Student-T
- [X] Uniform

I believe that the `.cdf` for Beta, Gamma, F, Student-T cannot be computed currently.
