### ISSUE TITLE
TransformedDistribution.cdf() ignores axis reversals

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#127]
There is a bug in `TransformedDistribution.cdf()` and `.icdf()` where an assumption is made that the transform is monotone increasing rather than monotone decreasing. This came up in https://github.com/pytorch/pytorch/pull/4950 because an `AffineTransform` set `scale < 0`. I'm not sure what is the right thing to do here, i.e. whether there is a generic method to determine whether a transform is monotone increasing or decreasing.

See discussion at https://github.com/pytorch/pytorch/pull/4950#issuecomment-364510835

**Comment by vishwakftw** [comment]
In both cases, the function is invertible, thus telling us that the `.cdf` and `.icdf` methods are _mathematically_ valid. In fact, for Gumbel, the scale was -1, in one of the affine transformations, and this didn't cause any issues.

**Comment by fritzo** [comment]
Hmm I agree that any `.icdf() : [0,1] -> dist.codomain` is useful, but it is standard to define cdf as monotonic increasing `$\int_\{-\infty}^x p(t) dt$`. I think some users will expect this, and it would be good to fix if we can figure out how to.

I believe `Gumbel` bypasses this issue because it has *two* `AffineTransforms` that each reverse the direction, so the signs cancel and `.cdf()` is monotonic increasing.

**Comment by vishwakftw** [comment]
I think I see the issue here. It is about defining the monotonicity of the resulting `.cdf`. CDFs are always monotonically increasing. This means that such a transform is actually invalid (?) (need confirmation on that).

**Comment by vishwakftw** [comment]
Implementation wise, this would require adding a check in the `TransformedDistribution`, where we check with all transforms in order to see if this monotonicity is violated.

**Comment by fritzo** [comment]
Oh sign-reversing transforms are perfectly valid but we should change the `.cdf()` method to something like
```py
class TransformedDistribution(object):
    def cdf(self, value):
        sign = 1
        for transform in self.transforms[::-1]:
            value = transform.inv(value)
            sign *= transform.sign
        value = self.base_dist.cdf(value)
        return sign * (value - 0.5) + 0.5

class Transform(object):
    sign = 1  # assume monotonic increasing by default

class AffiineTransform(Transform):
    @property
    def sign(self):
        return torch.sign(self.scale)
```

**Comment by vishwakftw** [comment]
Yes, I think that should work. And sign-reversing transforms are existent (sorry about earlier), since the change of variable method for transforms will accommodate for that by using an absolute value function.

**Comment by vishwakftw** [comment]
Closed in favour of https://github.com/pytorch/pytorch/pull/5172 .
