### ISSUE TITLE
Boundary Checking for Distributions

### ISSUE THREAD

**Issue by vishwakftw** [probtorch/pytorch#132]
This refers to issues https://github.com/pytorch/pytorch/issues/5227 and https://github.com/pytorch/pytorch/issues/5248 .

For the former issue, I could come up with a simple alteration to https://github.com/pytorch/pytorch/blob/master/torch/distributions/categorical.py#L52

```python
batch_shape = self._param.size()[:-1] if self._param.ndimension() > 1 else torch.Size()
```

**Comment by vishwakftw** [comment]
cc @fritzo

**Comment by alicanb** [comment]
@vishwakftw can you reproduce https://github.com/pytorch/pytorch/issues/5227 ?

**Comment by vishwakftw** [comment]
Yes, I was able to. Actually, the `Categorical` instance is not a problem, just the `sample` method.

**Comment by fritzo** [comment]
Whoa is `torch.Size()` slicing buggy? I don't see the difference between
```py
self._param.size()[:-1]
```
and
```py
self._param.size()[:-1] if self._param.ndimension() > 1 else torch.Size()
```
since `len(self._param.shape) >= 1` in all cases.

**Comment by vishwakftw** [comment]
If `self._param.ndimension() == 1`, then `self._param.size()[:-1]` returns `torch.Size([])` instead of `torch.Size()`. Only the latter seems to works, I think.

**Comment by fritzo** [comment]
That's a bug in `torch.Size()`, not a bug in torch.distributions.

**Comment by vishwakftw** [comment]
Oh okay, I thought I should write a temporary fix for it while I doing this as well.

**Comment by fritzo** [comment]
```py
>>> torch.Size() == torch.Size([])
True
```

**Comment by fritzo** [comment]
I think it's actually a bug in `.view()`:
```py
>>> torch.Tensor([0]).view(torch.Size())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: invalid argument 2: size '[]' is invalid for input with 1 elements at /Users/fritzobermeyer/pytorch-dev/2.7/aten/src/TH/THStorage.c:41
```

**Comment by vishwakftw** [comment]
In that case, I will revert this change alone. Sorry about the confusion.

**Comment by vishwakftw** [comment]
Closing in favour of https://github.com/pytorch/pytorch/pull/5358
