### ISSUE TITLE
Update Documentation for Distributions

### ISSUE THREAD

**Issue by vishwakftw** [probtorch/pytorch#136]
This should support the new API after Tensors and Variables have been merged.

cc: @fritzo

**Comment by fritzo** [comment]
@vishwakftw it looks like PyTorch may release in a couple weeks. Want to work on a docs PR with me? I'll cc you if I put up a draft PR.

**Comment by vishwakftw** [comment]
I think I have cleaned up torch.distributions. Have a look at the recent PR that was merged in pytorch/master https://github.com/pytorch/pytorch/pull/8046 . Based on that, I am closing this issue.
