### ISSUE TITLE
Disable covariance_matrix and precision_matrix constraints in mvn

### ISSUE THREAD

**Issue by fehiepsi** [probtorch/pytorch#146]
The covariance_matrix validation requires us to compute eigenvalues and the precision_matrix computation requires us to compute the inverse of `scale_tril`. They are slow because they are O(N^3) complexity and unnecessary if we know `scale_tril` (from [Sylvester's law](https://en.wikipedia.org/wiki/Sylvester%27s_law_of_inertia), we know that the eigenvalues of the covariance_matrix are positive if its scale_tril has all positive terms in its diagonal). In addition, in the current implementation of Pytorch most computations (except `variance`, which can also be computed from `scale_tril`) such as `rsample` and `log_prob` only require `scale_tril` to compute. So I think that it is better to disable them for both reasons: speed and unnecessary.

**Comment by tbrx** [comment]
Are you suggesting we disable the validation, or disable them as ways of parameterizing the MVN entirely?

Definitely `scale_tril` is going to be far more performant than the other options. We should probably make this more clear in the docs.

**Comment by fehiepsi** [comment]
I just suggest we disable the validation (by removing related constraints). It is helpful to have them in `init` and `lazy_property` because people usually use them without thinking about the scale_tril.

**Comment by fritzo** [comment]
> by removing related constraints

That would violate our contract on`.arg_constraints` is: if any (even optional) arg can be constrained then it appears in `.arg_constraints`. I suggest we instead figure out how to detect whether a lazy property has been constructed, and filter them out of [the validation loop](https://github.com/pytorch/pytorch/blob/master/torch/distributions/distribution.py#L30).

**Comment by fritzo** [comment]
It looks like we can simply
```diff
        if self._validate_args:
            for param, constraint in self.arg_constraints.items():
+               if param not in self.__dict__:
+                   continue
                if not constraints.is_dependent(constraint):
                    if not constraint.check(self.__getattribute__(param)).all():
                        raise ValueError("The parameter {} has invalid values".format(param))
```

**Comment by fehiepsi** [comment]
Thank @fritzo! This is solved by https://github.com/pytorch/pytorch/pull/6666 (nice number).
