### ISSUE TITLE
Implement Concrete Distribution

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#2]

**Comment by fritzo** [comment]
See example implementation by @rachtsingh at https://github.com/uber/pyro/pull/588

**Comment by rachtsingh** [comment]
Will port after https://github.com/pytorch/pytorch/pull/4771 is merged.

**Comment by rachtsingh** [comment]
Implemented here: https://github.com/probtorch/pytorch/pull/113

**Comment by alicanb** [comment]
closed via #113
