### ISSUE TITLE
Revise shape semantics of all distributions

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#30]
We will adapt `tf.distribution` shape semantics `(sample_shape, batch_shape, event_shape)`. See [design doc](https://docs.google.com/document/d/1wnABg0cdyaVMr-Xqz_brHBwnPJuzTeSk3Oqko2HHSfE/edit#heading=h.t6s7ftmgy2g9) for details.

**Comment by fritzo** [comment]
Is this done as of https://github.com/pytorch/pytorch/pull/4193 ?

**Comment by neerajprad** [comment]
> Is this done as of pytorch#4193 ?

Yes, we can close this and incorporate this into all new distributions.
