### ISSUE TITLE
Rename parameters to match TensorFlow Distributions

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#34]
To make it easy to port models between PyTorch and TensorFlow, it would be great if `torch.distributions` used the same distribution names and parameter names as `tf.contrib.distributions`.

- [x] `Categorical(probs)`
- [x] `Normal(loc, scale)`
- [x] `Dirichlet(concentration)`
- [x] `Beta(concentration1, concentration0)`
- [x] `Gamma(concentration, rate)`
- [x] `Exponential(rate)`
- [ ] What else? See [TF Distributions docs](https://www.tensorflow.org/api_docs/python/tf/distributions)

**Comment by alicanb** [comment]
Let's take care of the multiple parameterization here as well? e.g. `Gamma(concentration, rate, theta)`?

**Comment by alicanb** [comment]
closed via https://github.com/pytorch/pytorch/pull/4688

**Comment by ragulpr** [comment]
Is it bikeshedding to take this opportunity to add deprecation notice for `NLloss` in favor of `bernoulliNLLLoss`? Naming here always confuses me 😄
