### ISSUE TITLE
Implement analytic KL divergence methods

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#37]
Mirror of https://github.com/pytorch/pytorch/issues/4330

Framework: https://github.com/pytorch/pytorch/pull/4525
Implementations: https://github.com/probtorch/pytorch/pull/77

**Comment by vishwakftw** [comment]
Based on https://github.com/pytorch/pytorch/pull/4525 and https://github.com/pytorch/pytorch/pull/4638, should not this be closed? Now that the framework is ready, I think anyone can add.

**Comment by fritzo** [comment]
@vishwakftw Feel free to clean up issues. Sometimes we forget to close things that are done.
