### ISSUE TITLE
Implement Multinomial Distribution

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#4]
~~Depends on https://github.com/pytorch/pytorch/issues/3764 (Renaming `Multinomial` to `Categorical`)~~

Reference implementation: https://github.com/uber/pyro/blob/dev/pyro/distributions/multinomial.py

**Comment by fritzo** [comment]
@alicanb how is this going? I forgot to mention we have a [reference implementation](https://github.com/uber/pyro/blob/dev/pyro/distributions/multinomial.py) in Pyro.

**Comment by alicanb** [comment]
I'm almost done, I got the `log_prob` (thanks to your ref) and `sample`, all left is `entropy` and tests.

**Comment by fritzo** [comment]
Feel free to leave `.entropy()` not implemented and instead allow `NotImplementedError` in `TestDistributionShapes.test_entropy_shape()`:
```diff
- actual_shape = dist.entropy().size()
+ try:
+     actual_shape = dist.entropy().size()
+ except NotImplementedError:
+     continue
```

**Comment by fritzo** [comment]
Hi Alican, one detail that just came up in Pyro is the ability to score a batch of multinomials with different `n` in each batch. This came up in document modeling with variants of LDA in Pyro. We're training on batches of documents each with a different word count. While Pyro's `.sample()` method fixes a single `n` for each sample, the `.log_pdf()` method ([code](https://github.com/uber/pyro/blob/d751c45/pyro/distributions/multinomial.py#L80)) conveniently supports different `n` in each document. It would be great to preserve this feature and document it in the PyTorch implementation.

**Comment by fritzo** [comment]
Also, feel free to copy Pyro's [test examples](https://github.com/uber/pyro/blob/89d6cb8/tests/distributions/conftest.py#L141).

**Comment by fritzo** [comment]
@alicanb how's this going? We're about to switch Pyro over to using PyTorch distributions. Can I help in any way to finish Multinomial? I'm happy to push docs or whatever you'd like to this branch.

**Comment by alicanb** [comment]
Can you help me fix the failing test I mentioned? I tried the lambda trick you suggested, it fixes the 1d test for `logit` input but `gradcheck_log_prob` still fails for 2D `probs`

**Comment by alicanb** [comment]
Once we get this done, `Binomial` is very easy to implement

**Comment by fritzo** [comment]
Sure I'll take a look today at the failing test.

**Comment by alicanb** [comment]
closed via https://github.com/pytorch/pytorch/pull/4624
