### ISSUE TITLE
Implement Binomial distribution

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#42]

**Comment by alicanb** [comment]
I am taking a shot at this.
Sampling from this as a sum of Bernoulli wouldn't be too effective for larger total_count. I'm considering writing a rejection sampler in C @fritzo, what do you think?

**Comment by fritzo** [comment]
I'd recommend implementing `Multinomial` first and then implement `Binomial` as a special case of `Multinomial` (in the same way that `Beta` is implemented as special case of `Dirichlet`). I'd also recommend implementing both distributions with small-n assumptions (using `torch.multinomial()` at first?), and address computational concerns in a follow-up PR.

I'm not sure the best sampling scheme for large n, but a rejection sampler sounds reasonable.

**Comment by vishwakftw** [comment]
I am closing this issue, since `Binomial` is merged into `pytorch/master`.
