### ISSUE TITLE
change torch.multinomial to torch.categorical

### ISSUE THREAD

**Issue by alicanb** [probtorch/pytorch#46]
Similar argument to distributions.Multinomial->distributions.Categorical

**Comment by fritzo** [comment]
Related:
- https://github.com/pytorch/pytorch/issues/4115
- https://github.com/pytorch/pytorch/issues/3764

I agree that it would be nice to have a high-quality random multinomial implementation. There is some unfortunate confusion in that many libraries implement random categorical samplers but name them multinomial samplers: PyTorch, Numpy, TensorFlow. On the one hand it would be nice to have an actual multinomial; on the other hand it would be nice to follow the naming convention of other libraries (even if that convention is not mathematically correct).

**Comment by apaszke** [comment]
I don't think we'll do this. Not only others make the same mistake, it would also be quite a breaking change. It wasn't the same for `torch.distributions` because they have been newly introduced and were never part of any release.

**Comment by alicanb** [comment]
Alrighty then 😄

**Comment by neerajprad** [comment]
FYI - multinomial in tensorflow 2.0 is being renamed to categorical.
