### ISSUE TITLE
Implement Pareto distribution

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#62]
Mirror of https://github.com/pytorch/pytorch/issues/4434

Suggested by @vishwakftw

Once we have Bijectors, this should be easy to do with an `ExpBijector` and an `AffineBijector`, since for `X ~ Exp(alpha)`, transforming `Y = xm exp(X)` makes `Y ~ Pareto(xm, alpha)`.

**Comment by vishwakftw** [comment]
With the lack these features (temporarily), could I just implement the distribution using the quantile?

**Comment by fritzo** [comment]
Sure, don't let lack of `Bijector` hold you back. I'm mostly building up evidence that `Bijector`s would simplify lots of things.

**Comment by vishwakftw** [comment]
Okay thank you. Just one more clarification, where do I issue the PR?

**Comment by fritzo** [comment]
We've been using a two-stage review process to ease the workload for PyTorch folks:
1. First issue a PR against probtorch/pytorch master. We review each others PRs for statistical correctness and documentation etc. When this is accepted, **Close** (do not merge) this PR, then
2. Open a PR against pytorch/pytorch master and `cc @apaszke` who is our main reviewer for PyTorch code compliance.

**Comment by fritzo** [comment]
Also you can see what files need to be changed by looking at an existing PR like `Chi2`: https://github.com/pytorch/pytorch/pull/4425/files

**Comment by vishwakftw** [comment]
@fritzo Thanks for the references.
