### ISSUE TITLE
Implement Concrete distribution

### ISSUE THREAD

**Issue by alicanb** [probtorch/pytorch#74]

**Comment by fritzo** [comment]
Duplicate of #2. See example implementation by @rachtsingh at uber/pyro#588

**Comment by alicanb** [comment]
Sorry, my bad

**Comment by fritzo** [comment]
It's nice that we're getting so much done we lose track of what remains :wink:

**Comment by rachtsingh** [comment]
Ah yeah, let's port this after Bijectors land? I think I still need to write some tests, but the failures were PyTorch 0.3 stuff.
