### ISSUE TITLE
Add .shape properties to all distributions

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#8]

**Comment by jwvdm** [comment]
Should this be called `shape` or `size`? On the one hand, `size` is more similar to what PyTorch already provides for Tensors. On the other hand, `size()` is a method, not a property.

**Comment by fritzo** [comment]
`shape` seems preferable since (1) PyTorch is moving towards the numpy api (already has partial support for shape), and (2) edward uses shape so code will be more interchangeable.
