### ISSUE TITLE
Implement ExponentialFamily base class

### ISSUE THREAD

**Issue by fritzo** [probtorch/pytorch#96]
Consider implementing an `ExponentialFamily` class inserted in the class hierarchy between `Distribution` and e.g. `Normal` and `Exponential` distributions. If this class defined two methods `.natural_params()` and `.log_normalizer()`, then we might be able to systematically compute entropy and kl divergences for any derived or pair of derived classes. While these computations might be inefficient (requiring `grad()` under the hood), they could at least lead to a generic set of tests that are cheaper than our current monte carlo tests for `.entropy()` and `kl_divergence(-,-)`.

```py
class ExponentialFamily(Distribution):
   def natural_params(self):
        raise NotImplementedError
   def log_normalizer(self):
        raise NotImplementedError

class Normal(ExoponentialFamily):
    ...
```

## References

[pdf](https://pdfs.semanticscholar.org/fab3/337bcac9d026bb0e370cc644c46823e574c9.pdf) Nielson, Nock (2010) ENTROPIES AND CROSS-ENTROPIES OF EXPONENTIAL FAMILIES

**Comment by vishwakftw** [comment]
@fritzo Please have a look at this [gist](https://gist.github.com/vishwakftw/a048b9ad64e2342dbd11d4edb645b0cb). I would like to know if I am on the right track.

**Comment by fritzo** [comment]
@vishwakftw I think it would be better to implement this as an abstract base class with all work done in the methods. This way this extra class has near-zero overhead for existing use cases. We definitely do not want to perform any work in an `__init__` method.
```py
from torch.autograd import grad

class ExponentialFamily(Distribution):
    def natural_params(self):
        """Abstract method. Returns a tuple of Variables."""
        raise NotImplementedError
    def log_normalizer(self):
        """Abstract method. Returns a Variable of `batch_shape`"""
        raise NotImplementedError
    def entropy(self):
        nparams = self.natural_params
        lnorm = self.log_normalizer()
        grads = grad(lnorm.sum(), nparams)
        result = lnorm.clone()
        for p, g in zip(nparams, grads):
            result -= torch.dot(p, g)
        return result

class Normal(ExponentialFamily):
    ...all existing methods...
    def natural_params(self):
        return self._natural_params
    @lazy_property
    def _natural_params(self):
        return (Variable(self.loc / self.scale.pow(2), requires_grad=True),
                Variable(-0.5 * self.scale.pow(2).reciprocal(), requires_grad=True))
    def log_normalizer(self):
        x, y = self._natural_params
        return -0.25 * x.pow(2) / y + 0.5 * torch.log(-math.pi / y)
```

**Comment by vishwakftw** [comment]
Closed in favour of https://github.com/pytorch/pytorch/pull/4876.
